//
//  This CSharp output file generated by Gardens Point LEX
//  Gardens Point LEX (GPLEX) is Copyright (c) John Gough, QUT 2006-2014.
//  Output produced by GPLEX is the property of the user.
//  See accompanying file GPLEXcopyright.rtf.
//
//  GPLEX Version:  1.2.2
//  Machine:  NB-PLEOTZS
//  DateTime: 15.11.2021 12:40:30
//  UserName: PloetzS
//  GPLEX input file <gppg.lex - 09.11.2021 17:26:29>
//  GPLEX frame file <embedded resource>
//
//  Option settings: unicode, verbose, parser, stack, minimize
//  Option settings: classes, compressMap, compressNext, persistBuffer, noEmbedBuffers
//  Fallback code page: Raw 8-bit binary
//

//
// Revised backup code
// Version 1.2.1 of 24-June-2013
//
//
#define BACKUP
#define LEFTANCHORS
#define STACK
#define PERSIST

using System;
using System.IO;
using System.Text;
using System.Globalization;
using System.Collections.Generic;
using System.Runtime.Serialization;
using System.Diagnostics.CodeAnalysis;

using QUT.GplexBuffers;
using System.Collections;
using QUT.GPGen.Parser;

namespace QUT.GPGen.Lexers
{   
    /// <summary>
    /// Summary Canonical example of GPLEX automaton
    /// </summary>
    
#if STANDALONE
    //
    // These are the dummy declarations for stand-alone GPLEX applications
    // normally these declarations would come from the parser.
    // If you declare /noparser, or %option noparser then you get this.
    //

     internal enum Token
    { 
      EOF = 0, maxParseToken = int.MaxValue 
      // must have at least these two, values are almost arbitrary
    }

     internal abstract class ScanBase
    {
        [SuppressMessage("Microsoft.Naming", "CA1709:IdentifiersShouldBeCasedCorrectly", MessageId = "yylex")]
        [SuppressMessage("Microsoft.Naming", "CA1704:IdentifiersShouldBeSpelledCorrectly", MessageId = "yylex")]
        public abstract int yylex();

        [SuppressMessage("Microsoft.Naming", "CA1709:IdentifiersShouldBeCasedCorrectly", MessageId = "yywrap")]
        [SuppressMessage("Microsoft.Naming", "CA1704:IdentifiersShouldBeSpelledCorrectly", MessageId = "yywrap")]
        protected virtual bool yywrap() { return true; }

#if BABEL
        protected abstract int CurrentSc { get; set; }
        // EolState is the 32-bit of state data persisted at 
        // the end of each line for Visual Studio colorization.  
        // The default is to return CurrentSc.  You must override
        // this if you want more complicated behavior.
        public virtual int EolState { 
            get { return CurrentSc; }
            set { CurrentSc = value; } 
        }
    }
    
     internal interface IColorScan
    {
        void SetSource(string source, int offset);
        int GetNext(ref int state, out int start, out int end);
#endif // BABEL
    }

#endif // STANDALONE
    
    // If the compiler can't find the scanner base class maybe you
    // need to run GPPG with the /gplex option, or GPLEX with /noparser
#if BABEL
     internal sealed partial class Scanner : ScanBase, IColorScan
    {
        private ScanBuff buffer;
        int currentScOrd;  // start condition ordinal
        
        protected override int CurrentSc 
        {
             // The current start state is a property
             // to try to avoid the user error of setting
             // scState but forgetting to update the FSA
             // start state "currentStart"
             //
             get { return currentScOrd; }  // i.e. return YY_START;
             set { currentScOrd = value;   // i.e. BEGIN(value);
                   currentStart = startState[value]; }
        }
#else  // BABEL
     internal sealed partial class Scanner : ScanBase
    {
        private ScanBuff buffer;
        int currentScOrd;  // start condition ordinal
#endif // BABEL
        
        /// <summary>
        /// The input buffer for this scanner.
        /// </summary>
        [SuppressMessage("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        public ScanBuff Buffer { get { return buffer; } }
        
        private static int GetMaxParseToken() {
     System.Reflection.FieldInfo f = typeof(Token).GetField("maxParseToken");
            return (f == null ? int.MaxValue : (int)f.GetValue(null));
        }
        
        static int parserMax = GetMaxParseToken();
        
        enum Result {accept, noMatch, contextFound};

        const int maxAccept = 86;
        const int initial = 87;
        const int eofNum = 0;
        const int goStart = -1;
        const int INITIAL = 0;
        const int TheRules = 1;
        const int TheEpilog = 2;
        const int GetPath = 3;
        const int Prolog = 4;
        const int Action = 5;
        const int Comment = 6;
        const int CodeBlock = 7;
        const int ShouldBeBlank = 8;

#region user code
/* gppg.lex: Author: John Gough, August 2008 */
/* 
 * Expected file format is Unicode. In the event that no 
 * byte order mark prefix is found, revert to raw bytes.
 */
/* --------------------------- */
#endregion user code

        int state;
        int currentStart = startState[0];
        int code;      // last code read
        int cCol;      // column number of code
        int lNum;      // current line number
        //
        // The following instance variables are used, among other
        // things, for constructing the yylloc location objects.
        //
        int tokPos;        // buffer position at start of token
        int tokCol;        // zero-based column number at start of token
        int tokLin;        // line number at start of token
        int tokEPos;       // buffer position at end of token
        int tokECol;       // column number at end of token
        int tokELin;       // line number at end of token
        string tokTxt;     // lazily constructed text of token
#if STACK          
        private Stack<int> scStack = new Stack<int>();
#endif // STACK

#region ScannerTables
    struct Table {
        public int min; public int rng; public int dflt;
        public short[] nxt;
        public Table(int m, int x, int d, short[] n) {
            min = m; rng = x; dflt = d; nxt = n;
        }
    };

    static int[] startState = new int[] {87, 106, 124, 127, 124, 133, 
        61, 134, 153, 0};

   static int[] anchorState = new int[] {88, 107, 124, 127, 132, 133, 
        61, 135, 153, 0};

#region CompressedCharacterMap
    //
    // There are 25 equivalence classes
    // There are 2 character sequence regions
    // There are 1 tables, 126 entries
    // There are 1 runs, 0 singletons
    // Decision tree depth is 1
    //
    static sbyte[] mapC0 = new sbyte[126] {
/*     '\0' */ 5, 15, 15, 15, 15, 15, 15, 5, 5, 2, 0, 5, 5, 4, 15, 15, 
/*   '\x10' */ 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 
/*   '\x20' */ 14, 15, 20, 15, 15, 6, 15, 13, 15, 15, 3, 15, 21, 15, 21, 1, 
/*      '0' */ 10, 17, 17, 17, 17, 17, 17, 17, 9, 9, 21, 21, 21, 23, 21, 15, 
/*      '@' */ 22, 12, 12, 12, 12, 12, 12, 8, 8, 8, 8, 8, 8, 8, 8, 8, 
/*      'P' */ 8, 8, 8, 8, 8, 19, 8, 8, 8, 8, 8, 21, 16, 21, 15, 8, 
/*      '`' */ 15, 12, 12, 12, 12, 12, 12, 8, 8, 8, 8, 8, 8, 8, 8, 8, 
/*      'p' */ 8, 8, 8, 8, 8, 18, 8, 8, 11, 8, 8, 7, 21, 24 };

    static sbyte MapC(int code)
    { // '\0' <= code <= '\U0010FFFF'
      if (code < 126) // '\0' <= code <= '}'
        return mapC0[code - 0];
      else // '~' <= code <= '\U0010FFFF'
        return (sbyte)15;
    }
#endregion

    static Table[] NxS = new Table[154] {
/* NxS[   0] */ new Table(0, 0, 0, null), // Shortest string ""
/* NxS[   1] */ // Shortest string "/"
      new Table(1, 3, -1, new short[] {19, -1, 20}),
/* NxS[   2] */ new Table(0, 0, -1, null), // Shortest string "*"
/* NxS[   3] */ // Shortest string "^%"
      new Table(24, 21, 14, new short[] {18, -1, 14, -1, 14, -1, 
          14, 15, 16, 17, 14, 14, 17, 17, 14, -1, 14, 14, 14, 17, 17}),
/* NxS[   4] */ new Table(0, 0, -1, null), // Shortest string "{"
/* NxS[   5] */ // Shortest string "G"
      new Table(8, 12, -1, new short[] {5, 5, 5, 5, 5, -1, 
          -1, -1, -1, 5, 5, 5}),
/* NxS[   6] */ // Shortest string "8"
      new Table(9, 9, -1, new short[] {6, 6, -1, -1, -1, -1, 
          -1, -1, 6}),
/* NxS[   7] */ // Shortest string "0"
      new Table(9, 9, -1, new short[] {6, 6, 105, -1, -1, -1, 
          -1, -1, 6}),
/* NxS[   8] */ // Shortest string "'"
      new Table(0, 17, 91, new short[] {-1, 91, -1, 91, -1, -1, 
          91, 91, 91, 91, 91, 91, 91, -1, 91, 91, 92}),
/* NxS[   9] */ // Shortest string "\""
      new Table(16, 15, 89, new short[] {90, 89, 89, 89, 11, 89, 
          89, 89, 89, 10, 89, -1, 89, 10, -1}),
/* NxS[  10] */ new Table(0, 0, -1, null), // Shortest string "\"\r"
/* NxS[  11] */ new Table(0, 0, -1, null), // Shortest string "\"\""
/* NxS[  12] */ new Table(0, 0, -1, null), // Shortest string "'/'"
/* NxS[  13] */ // Shortest string "0x8"
      new Table(9, 9, -1, new short[] {13, 13, -1, 13, -1, -1, 
          -1, -1, 13}),
/* NxS[  14] */ new Table(0, 0, -1, null), // Shortest string "%/"
/* NxS[  15] */ new Table(0, 0, -1, null), // Shortest string "^%%"
/* NxS[  16] */ new Table(0, 0, -1, null), // Shortest string "^%{"
/* NxS[  17] */ // Shortest string "^%G"
      new Table(8, 12, -1, new short[] {17, 17, 17, 17, 17, -1, 
          -1, -1, -1, 17, 17, 17}),
/* NxS[  18] */ new Table(0, 0, -1, null), // Shortest string "^%}"
/* NxS[  19] */ // Shortest string "//"
      new Table(0, 5, 19, new short[] {-1, 19, 19, 19, -1}),
/* NxS[  20] */ new Table(0, 0, -1, null), // Shortest string "/*"
/* NxS[  21] */ // Shortest string "%"
      new Table(0, 20, 14, new short[] {-1, 14, -1, 14, -1, 14, 
          14, 14, 22, 14, 14, 22, 22, 14, -1, 14, 14, 14, 22, 22}),
/* NxS[  22] */ // Shortest string "%G"
      new Table(8, 12, -1, new short[] {22, 22, 22, 22, 22, -1, 
          -1, -1, -1, 22, 22, 22}),
/* NxS[  23] */ // Shortest string "^%"
      new Table(24, 21, 14, new short[] {18, -1, 14, -1, 14, -1, 
          14, 31, 14, 32, 14, 14, 32, 32, 14, -1, 14, 14, 14, 32, 32}),
/* NxS[  24] */ new Table(0, 0, -1, null), // Shortest string "{"
/* NxS[  25] */ // Shortest string "^G"
      new Table(8, 12, -1, new short[] {25, 25, 25, 25, 25, -1, 
          -1, -1, -1, 25, 25, 25}),
/* NxS[  26] */ // Shortest string "'"
      new Table(0, 17, 110, new short[] {-1, 110, -1, 110, -1, -1, 
          110, 110, 110, 110, 110, 110, 110, -1, 110, 110, 111}),
/* NxS[  27] */ // Shortest string "\""
      new Table(16, 15, 108, new short[] {109, 108, 108, 108, 29, 108, 
          108, 108, 108, 10, 108, -1, 108, 10, -1}),
/* NxS[  28] */ new Table(0, 0, -1, null), // Shortest string ","
/* NxS[  29] */ new Table(0, 0, -1, null), // Shortest string "\"\""
/* NxS[  30] */ new Table(0, 0, -1, null), // Shortest string "'/'"
/* NxS[  31] */ new Table(0, 0, -1, null), // Shortest string "^%%"
/* NxS[  32] */ // Shortest string "%G"
      new Table(8, 12, -1, new short[] {32, 32, 32, 32, 32, -1, 
          -1, -1, -1, 32, 32, 32}),
/* NxS[  33] */ // Shortest string "%"
      new Table(0, 20, 14, new short[] {-1, 14, -1, 14, -1, 14, 
          14, 14, 32, 14, 14, 32, 32, 14, -1, 14, 14, 14, 32, 32}),
/* NxS[  34] */ // Shortest string "G"
      new Table(8, 12, -1, new short[] {34, 34, 34, 34, 34, -1, 
          -1, -1, -1, 34, 34, 34}),
/* NxS[  35] */ // Shortest string "/"
      new Table(1, 3, -1, new short[] {39, -1, 40}),
/* NxS[  36] */ new Table(0, 0, -1, null), // Shortest string "\t"
/* NxS[  37] */ // Shortest string "%"
      new Table(0, 15, 14, new short[] {-1, 14, -1, 14, -1, 14, 
          14, 14, 14, 14, 14, 14, 14, 14, -1}),
/* NxS[  38] */ // Shortest string "\""
      new Table(16, 15, 125, new short[] {126, 125, 125, 125, -1, 125, 
          125, 125, 125, 10, 125, -1, 125, 10, -1}),
/* NxS[  39] */ // Shortest string "//"
      new Table(0, 5, 39, new short[] {-1, 39, 39, 39, -1}),
/* NxS[  40] */ new Table(0, 0, -1, null), // Shortest string "/*"
/* NxS[  41] */ new Table(0, 0, -1, null), // Shortest string ""
/* NxS[  42] */ // Shortest string "/"
      new Table(0, 15, 43, new short[] {-1, 19, -1, 57, -1, 43, 
          43, 43, 43, 43, 43, 43, 43, 43, -1}),
/* NxS[  43] */ // Shortest string "*"
      new Table(0, 15, 43, new short[] {-1, 43, -1, 43, -1, 43, 
          43, 43, 43, 43, 43, 43, 43, 43, -1}),
/* NxS[  44] */ // Shortest string "\r"
      new Table(0, 1, -1, new short[] {41}),
/* NxS[  45] */ // Shortest string "\""
      new Table(14, 17, 45, new short[] {130, 45, 54, 45, 45, 45, 
          55, 45, 45, 45, 45, 10, 45, -1, 45, 10, 43}),
/* NxS[  46] */ // Shortest string "@"
      new Table(14, 16, 43, new short[] {-1, 43, 43, 43, 43, 43, 
          48, 43, 43, 43, 43, -1, 43, -1, 43, -1}),
/* NxS[  47] */ // Shortest string "="
      new Table(0, 15, 47, new short[] {-1, 47, -1, 47, -1, 47, 
          47, 47, 47, 47, 47, 47, 47, 47, -1}),
/* NxS[  48] */ // Shortest string "@\""
      new Table(14, 16, 48, new short[] {128, 48, 49, 48, 48, 48, 
          50, 48, 48, 48, 48, 128, 48, 128, 48, 128}),
/* NxS[  49] */ // Shortest string "@\"\\"
      new Table(14, 16, 48, new short[] {128, 48, 49, 48, 48, 48, 
          51, 48, 48, 48, 48, 128, 48, 128, 48, 128}),
/* NxS[  50] */ // Shortest string "@\"\""
      new Table(14, 16, 43, new short[] {-1, 43, 43, 43, 43, 43, 
          48, 43, 43, 43, 43, -1, 43, -1, 43, -1}),
/* NxS[  51] */ // Shortest string "@\"\\\""
      new Table(14, 16, 48, new short[] {128, 48, 49, 48, 48, 48, 
          51, 48, 48, 48, 48, 128, 48, 128, 48, 128}),
/* NxS[  52] */ // Shortest string "@\"\t\""
      new Table(20, 1, -1, new short[] {128}),
/* NxS[  53] */ // Shortest string "@\"\t\\\""
      new Table(16, 5, 128, new short[] {129, 128, 128, 128, 53}),
/* NxS[  54] */ // Shortest string "\"\\"
      new Table(0, 15, 45, new short[] {-1, 45, 130, 45, -1, 45, 
          45, 45, 45, 45, 45, 45, 45, 45, 130}),
/* NxS[  55] */ // Shortest string "\"\""
      new Table(0, 15, 43, new short[] {-1, 43, -1, 43, -1, 43, 
          43, 43, 43, 43, 43, 43, 43, 43, -1}),
/* NxS[  56] */ new Table(0, 0, -1, null), // Shortest string "\"\x20\""
/* NxS[  57] */ // Shortest string "/*"
      new Table(0, 15, 43, new short[] {-1, 43, -1, 43, -1, 43, 
          43, 43, 43, 43, 43, 43, 43, 43, -1}),
/* NxS[  58] */ // Shortest string "^%"
      new Table(14, 16, 14, new short[] {-1, 14, 14, 14, 14, 14, 
          14, 14, 14, 14, 59, -1, 14, -1, 14, -1}),
/* NxS[  59] */ new Table(0, 0, -1, null), // Shortest string "^%}"
/* NxS[  60] */ new Table(0, 0, -1, null), // Shortest string "}"
/* NxS[  61] */ // Shortest string ""
      new Table(20, 12, 62, new short[] {65, 62, 62, 62, 62, -1, 
          62, 62, 63, -1, 62, 64}),
/* NxS[  62] */ // Shortest string "/"
      new Table(0, 5, 62, new short[] {-1, 62, 62, -1, -1}),
/* NxS[  63] */ // Shortest string "*"
      new Table(1, 1, -1, new short[] {67}),
/* NxS[  64] */ // Shortest string "%"
      new Table(0, 5, 62, new short[] {-1, 62, 62, 14, -1}),
/* NxS[  65] */ // Shortest string "\""
      new Table(16, 15, 65, new short[] {66, 65, 65, 65, 62, 65, 
          65, 65, 65, 10, 65, 62, 125, 10, 62}),
/* NxS[  66] */ // Shortest string "\"\\"
      new Table(0, 5, 65, new short[] {-1, 65, 65, 125, -1}),
/* NxS[  67] */ new Table(0, 0, -1, null), // Shortest string "*/"
/* NxS[  68] */ // Shortest string "/"
      new Table(1, 3, -1, new short[] {19, -1, 20}),
/* NxS[  69] */ // Shortest string "^%"
      new Table(20, 19, 77, new short[] {14, 77, 14, 77, 79, 77, 
          14, 77, 77, 77, 77, 78, 14, 77, 77, 77, 77, 77, 14}),
/* NxS[  70] */ new Table(0, 0, -1, null), // Shortest string "{"
/* NxS[  71] */ // Shortest string "'"
      new Table(0, 17, 139, new short[] {-1, 139, -1, 139, -1, -1, 
          139, 139, 139, 139, 139, 139, 139, -1, 139, 139, 140}),
/* NxS[  72] */ // Shortest string "\""
      new Table(16, 15, 72, new short[] {138, 72, 72, 72, 76, 72, 
          72, 72, 72, 10, 72, -1, 72, 10, -1}),
/* NxS[  73] */ // Shortest string "@"
      new Table(20, 1, -1, new short[] {136}),
/* NxS[  74] */ new Table(0, 0, -1, null), // Shortest string "}"
/* NxS[  75] */ // Shortest string "@\"\\\""
      new Table(16, 5, 136, new short[] {137, 136, 136, 136, 75}),
/* NxS[  76] */ new Table(0, 0, -1, null), // Shortest string "\"\""
/* NxS[  77] */ // Shortest string "\t"
      new Table(20, 19, 77, new short[] {-1, 77, -1, 77, -1, 77, 
          -1, 77, 77, 77, 77, -1, -1, 77, 77, 77, 77, 77, -1}),
/* NxS[  78] */ new Table(0, 0, -1, null), // Shortest string "^%%"
/* NxS[  79] */ new Table(0, 0, -1, null), // Shortest string "^%}"
/* NxS[  80] */ // Shortest string "%"
      new Table(20, 19, 77, new short[] {14, 77, 14, 77, 14, 77, 
          14, 77, 77, 77, 77, 14, 14, 77, 77, 77, 77, 77, 14}),
/* NxS[  81] */ new Table(0, 0, -1, null), // Shortest string ""
/* NxS[  82] */ // Shortest string "/"
      new Table(1, 3, -1, new short[] {19, -1, 20}),
/* NxS[  83] */ new Table(0, 0, -1, null), // Shortest string "*"
/* NxS[  84] */ // Shortest string "\r"
      new Table(0, 1, -1, new short[] {81}),
/* NxS[  85] */ // Shortest string "%"
      new Table(0, 15, 14, new short[] {-1, 14, -1, 14, -1, 14, 
          14, 14, 14, 14, 14, 14, 14, 14, -1}),
/* NxS[  86] */ // Shortest string "\""
      new Table(16, 15, 125, new short[] {126, 125, 125, 125, -1, 125, 
          125, 125, 125, 10, 125, -1, 125, 10, -1}),
/* NxS[  87] */ // Shortest string ""
      new Table(13, 23, 5, new short[] {8, -1, 2, 2, 6, 5, 
          5, 9, 4, 2, 2, 4, -1, 1, -1, 2, -1, 2, 21, 4, 5, 6, 
          7}),
/* NxS[  88] */ // Shortest string "^"
      new Table(13, 23, 5, new short[] {8, -1, 2, 2, 6, 5, 
          5, 9, 4, 2, 2, 4, -1, 1, -1, 2, -1, 2, 3, 4, 5, 6, 
          7}),
/* NxS[  89] */ // Shortest string "\"/"
      new Table(16, 15, 89, new short[] {90, 89, 89, 89, 11, 89, 
          89, 89, 89, 10, 89, -1, 89, 10, -1}),
/* NxS[  90] */ // Shortest string "\"\\"
      new Table(0, 5, 89, new short[] {-1, 89, 89, 89, -1}),
/* NxS[  91] */ // Shortest string "'/"
      new Table(13, 1, -1, new short[] {12}),
/* NxS[  92] */ // Shortest string "'\\"
      new Table(10, 20, 91, new short[] {93, 94, 91, 91, 91, 91, 
          91, 93, 95, 96, 91, 91, 91, 91, 91, -1, 91, 91, 91, -1}),
/* NxS[  93] */ // Shortest string "'\\0"
      new Table(10, 8, -1, new short[] {104, -1, -1, 12, -1, -1, 
          -1, 104}),
/* NxS[  94] */ // Shortest string "'\\x"
      new Table(9, 9, -1, new short[] {103, 103, -1, 103, 12, -1, 
          -1, -1, 103}),
/* NxS[  95] */ // Shortest string "'\\u"
      new Table(9, 9, -1, new short[] {101, 101, -1, 101, 12, -1, 
          -1, -1, 101}),
/* NxS[  96] */ // Shortest string "'\\U"
      new Table(9, 9, -1, new short[] {97, 97, -1, 97, 12, -1, 
          -1, -1, 97}),
/* NxS[  97] */ // Shortest string "'\\U8"
      new Table(9, 9, -1, new short[] {98, 98, -1, 98, -1, -1, 
          -1, -1, 98}),
/* NxS[  98] */ // Shortest string "'\\U88"
      new Table(9, 9, -1, new short[] {99, 99, -1, 99, -1, -1, 
          -1, -1, 99}),
/* NxS[  99] */ // Shortest string "'\\U888"
      new Table(9, 9, -1, new short[] {100, 100, -1, 100, -1, -1, 
          -1, -1, 100}),
/* NxS[ 100] */ // Shortest string "'\\U8888"
      new Table(9, 9, -1, new short[] {101, 101, -1, 101, -1, -1, 
          -1, -1, 101}),
/* NxS[ 101] */ // Shortest string "'\\u8"
      new Table(9, 9, -1, new short[] {102, 102, -1, 102, -1, -1, 
          -1, -1, 102}),
/* NxS[ 102] */ // Shortest string "'\\u88"
      new Table(9, 9, -1, new short[] {103, 103, -1, 103, -1, -1, 
          -1, -1, 103}),
/* NxS[ 103] */ // Shortest string "'\\x8"
      new Table(9, 9, -1, new short[] {91, 91, -1, 91, -1, -1, 
          -1, -1, 91}),
/* NxS[ 104] */ // Shortest string "'\\00"
      new Table(10, 8, -1, new short[] {91, -1, -1, -1, -1, -1, 
          -1, 91}),
/* NxS[ 105] */ // Shortest string "0x"
      new Table(9, 9, -1, new short[] {13, 13, -1, 13, -1, -1, 
          -1, -1, 13}),
/* NxS[ 106] */ // Shortest string ""
      new Table(18, 22, 2, new short[] {34, 34, 27, 28, 2, 2, 
          28, -1, 1, -1, 2, -1, 2, 33, 24, 34, 2, 2, 34, 34, 26, -1}),
/* NxS[ 107] */ // Shortest string "^"
      new Table(18, 22, 2, new short[] {25, 25, 27, 28, 2, 2, 
          28, -1, 1, -1, 2, -1, 2, 23, 24, 25, 2, 2, 25, 25, 26, -1}),
/* NxS[ 108] */ // Shortest string "\"/"
      new Table(16, 15, 108, new short[] {109, 108, 108, 108, 29, 108, 
          108, 108, 108, 10, 108, -1, 108, 10, -1}),
/* NxS[ 109] */ // Shortest string "\"\\"
      new Table(0, 5, 108, new short[] {-1, 108, 108, 108, -1}),
/* NxS[ 110] */ // Shortest string "'/"
      new Table(13, 1, -1, new short[] {30}),
/* NxS[ 111] */ // Shortest string "'\\"
      new Table(10, 20, 110, new short[] {112, 113, 110, 110, 110, 110, 
          110, 112, 114, 115, 110, 110, 110, 110, 110, -1, 110, 110, 110, -1}),
/* NxS[ 112] */ // Shortest string "'\\0"
      new Table(10, 8, -1, new short[] {123, -1, -1, 30, -1, -1, 
          -1, 123}),
/* NxS[ 113] */ // Shortest string "'\\x"
      new Table(9, 9, -1, new short[] {122, 122, -1, 122, 30, -1, 
          -1, -1, 122}),
/* NxS[ 114] */ // Shortest string "'\\u"
      new Table(9, 9, -1, new short[] {120, 120, -1, 120, 30, -1, 
          -1, -1, 120}),
/* NxS[ 115] */ // Shortest string "'\\U"
      new Table(9, 9, -1, new short[] {116, 116, -1, 116, 30, -1, 
          -1, -1, 116}),
/* NxS[ 116] */ // Shortest string "'\\U8"
      new Table(9, 9, -1, new short[] {117, 117, -1, 117, -1, -1, 
          -1, -1, 117}),
/* NxS[ 117] */ // Shortest string "'\\U88"
      new Table(9, 9, -1, new short[] {118, 118, -1, 118, -1, -1, 
          -1, -1, 118}),
/* NxS[ 118] */ // Shortest string "'\\U888"
      new Table(9, 9, -1, new short[] {119, 119, -1, 119, -1, -1, 
          -1, -1, 119}),
/* NxS[ 119] */ // Shortest string "'\\U8888"
      new Table(9, 9, -1, new short[] {120, 120, -1, 120, -1, -1, 
          -1, -1, 120}),
/* NxS[ 120] */ // Shortest string "'\\u8"
      new Table(9, 9, -1, new short[] {121, 121, -1, 121, -1, -1, 
          -1, -1, 121}),
/* NxS[ 121] */ // Shortest string "'\\u88"
      new Table(9, 9, -1, new short[] {122, 122, -1, 122, -1, -1, 
          -1, -1, 122}),
/* NxS[ 122] */ // Shortest string "'\\x8"
      new Table(9, 9, -1, new short[] {110, 110, -1, 110, -1, -1, 
          -1, -1, 110}),
/* NxS[ 123] */ // Shortest string "'\\00"
      new Table(10, 8, -1, new short[] {110, -1, -1, -1, -1, -1, 
          -1, 110}),
/* NxS[ 124] */ // Shortest string ""
      new Table(20, 12, 36, new short[] {38, 36, 36, 36, 36, -1, 
          35, 36, 36, 36, 36, 37}),
/* NxS[ 125] */ // Shortest string "\"/"
      new Table(16, 15, 125, new short[] {126, 125, 125, 125, -1, 125, 
          125, 125, 125, 10, 125, -1, 125, 10, -1}),
/* NxS[ 126] */ // Shortest string "\"\\"
      new Table(0, 5, 125, new short[] {-1, 125, 125, 125, -1}),
/* NxS[ 127] */ // Shortest string ""
      new Table(14, 16, 43, new short[] {-1, 43, 43, 43, 43, 43, 
          45, 43, 46, 47, 43, 41, 42, -1, 43, 44}),
/* NxS[ 128] */ // Shortest string "@\"\t"
      new Table(16, 5, 128, new short[] {129, 128, 128, 128, 52}),
/* NxS[ 129] */ // Shortest string "@\"\t\\"
      new Table(16, 5, 128, new short[] {129, 128, 128, 128, 53}),
/* NxS[ 130] */ // Shortest string "\"\x20"
      new Table(16, 15, 130, new short[] {131, 130, 130, 130, 56, 130, 
          130, 130, 130, 10, 130, -1, 130, 10, -1}),
/* NxS[ 131] */ // Shortest string "\"\x20\\"
      new Table(0, 5, 130, new short[] {-1, 130, 130, 130, -1}),
/* NxS[ 132] */ // Shortest string "^"
      new Table(20, 12, 36, new short[] {38, 36, 36, 36, 36, -1, 
          35, 36, 36, 36, 36, 58}),
/* NxS[ 133] */ // Shortest string ""
      new Table(20, 12, 36, new short[] {38, 36, 36, 36, 60, -1, 
          35, 36, 36, 36, 36, 37}),
/* NxS[ 134] */ // Shortest string ""
      new Table(20, 19, 77, new short[] {72, 77, 73, 77, 74, 77, 
          68, 77, 77, 77, 77, 80, 70, 77, 77, 77, 77, 77, 71}),
/* NxS[ 135] */ // Shortest string "^"
      new Table(20, 19, 77, new short[] {72, 77, 73, 77, 74, 77, 
          68, 77, 77, 77, 77, 69, 70, 77, 77, 77, 77, 77, 71}),
/* NxS[ 136] */ // Shortest string "@\""
      new Table(16, 5, 136, new short[] {137, 136, 136, 136, 73}),
/* NxS[ 137] */ // Shortest string "@\"\\"
      new Table(16, 5, 136, new short[] {137, 136, 136, 136, 75}),
/* NxS[ 138] */ // Shortest string "\"\\"
      new Table(0, 5, 72, new short[] {-1, 72, 72, 72, -1}),
/* NxS[ 139] */ // Shortest string "'/"
      new Table(13, 1, -1, new short[] {76}),
/* NxS[ 140] */ // Shortest string "'\\"
      new Table(10, 20, 139, new short[] {141, 142, 139, 139, 139, 139, 
          139, 141, 143, 144, 139, 139, 139, 139, 139, -1, 139, 139, 139, -1}),
/* NxS[ 141] */ // Shortest string "'\\0"
      new Table(10, 8, -1, new short[] {152, -1, -1, 76, -1, -1, 
          -1, 152}),
/* NxS[ 142] */ // Shortest string "'\\x"
      new Table(9, 9, -1, new short[] {151, 151, -1, 151, 76, -1, 
          -1, -1, 151}),
/* NxS[ 143] */ // Shortest string "'\\u"
      new Table(9, 9, -1, new short[] {149, 149, -1, 149, 76, -1, 
          -1, -1, 149}),
/* NxS[ 144] */ // Shortest string "'\\U"
      new Table(9, 9, -1, new short[] {145, 145, -1, 145, 76, -1, 
          -1, -1, 145}),
/* NxS[ 145] */ // Shortest string "'\\U8"
      new Table(9, 9, -1, new short[] {146, 146, -1, 146, -1, -1, 
          -1, -1, 146}),
/* NxS[ 146] */ // Shortest string "'\\U88"
      new Table(9, 9, -1, new short[] {147, 147, -1, 147, -1, -1, 
          -1, -1, 147}),
/* NxS[ 147] */ // Shortest string "'\\U888"
      new Table(9, 9, -1, new short[] {148, 148, -1, 148, -1, -1, 
          -1, -1, 148}),
/* NxS[ 148] */ // Shortest string "'\\U8888"
      new Table(9, 9, -1, new short[] {149, 149, -1, 149, -1, -1, 
          -1, -1, 149}),
/* NxS[ 149] */ // Shortest string "'\\u8"
      new Table(9, 9, -1, new short[] {150, 150, -1, 150, -1, -1, 
          -1, -1, 150}),
/* NxS[ 150] */ // Shortest string "'\\u88"
      new Table(9, 9, -1, new short[] {151, 151, -1, 151, -1, -1, 
          -1, -1, 151}),
/* NxS[ 151] */ // Shortest string "'\\x8"
      new Table(9, 9, -1, new short[] {139, 139, -1, 139, -1, -1, 
          -1, -1, 139}),
/* NxS[ 152] */ // Shortest string "'\\00"
      new Table(10, 8, -1, new short[] {139, -1, -1, -1, -1, -1, 
          -1, 139}),
/* NxS[ 153] */ // Shortest string ""
      new Table(14, 18, 83, new short[] {-1, 83, 83, 83, 83, 83, 
          86, 83, 83, 83, 83, 81, 82, -1, 83, 84, 83, 85}),
    };

int NextState() {
    if (code == ScanBuff.EndOfFile)
        return eofNum;
    else
        unchecked {
            int rslt;
            int idx = MapC(code) - NxS[state].min;
            if (idx < 0) idx += 25;
            if ((uint)idx >= (uint)NxS[state].rng) rslt = NxS[state].dflt;
            else rslt = NxS[state].nxt[idx];
            return rslt;
        }
}

#endregion


#if BACKUP
        // ==============================================================
        // == Nested struct used for backup in automata that do backup ==
        // ==============================================================

        struct Context // class used for automaton backup.
        {
            public int bPos;
            public int rPos; // scanner.readPos saved value
            public int cCol;
            public int lNum; // Need this in case of backup over EOL.
            public int state;
            public int cChr;
        }
        
        private Context ctx = new Context();
#endif // BACKUP

        // ==============================================================
        // ==== Nested struct to support input switching in scanners ====
        // ==============================================================

		struct BufferContext {
            internal ScanBuff buffSv;
			internal int chrSv;
			internal int cColSv;
			internal int lNumSv;
		}

        // ==============================================================
        // ===== Private methods to save and restore buffer contexts ====
        // ==============================================================

        /// <summary>
        /// This method creates a buffer context record from
        /// the current buffer object, together with some
        /// scanner state values. 
        /// </summary>
        [SuppressMessage("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        BufferContext MkBuffCtx()
		{
			BufferContext rslt;
			rslt.buffSv = this.buffer;
			rslt.chrSv = this.code;
			rslt.cColSv = this.cCol;
			rslt.lNumSv = this.lNum;
			return rslt;
		}

        /// <summary>
        /// This method restores the buffer value and allied
        /// scanner state from the given context record value.
        /// </summary>
        [SuppressMessage("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        void RestoreBuffCtx(BufferContext value)
		{
			this.buffer = value.buffSv;
			this.code = value.chrSv;
			this.cCol = value.cColSv;
			this.lNum = value.lNumSv;
        } 
        // =================== End Nested classes =======================

#if !NOFILES
     internal Scanner(Stream file) {
            SetSource(file, -1); // unicode option
        }

        public Scanner(Stream file, string codepage) {
            SetSource(file, CodePageHandling.GetCodePage(codepage));
        }   
#endif // !NOFILES

     internal Scanner() { }

        private int readPos;

        void GetCode()
        {
            if (code == '\n')  // This needs to be fixed for other conventions
                               // i.e. [\r\n\205\u2028\u2029]
            { 
                cCol = -1;
                lNum++;
            }
            readPos = buffer.Pos;

            // Now read new codepoint.
            code = buffer.Read();
            if (code > ScanBuff.EndOfFile)
            {
#if (!BYTEMODE)
                if (code >= 0xD800 && code <= 0xDBFF)
                {
                    int next = buffer.Read();
                    if (next < 0xDC00 || next > 0xDFFF)
                        code = ScanBuff.UnicodeReplacementChar;
                    else
                        code = (0x10000 + ((code & 0x3FF) << 10) + (next & 0x3FF));
                }
#endif
                cCol++;
            }
        }

        void MarkToken()
        {
#if (!PERSIST)
            buffer.Mark();
#endif
            tokPos = readPos;
            tokLin = lNum;
            tokCol = cCol;
        }
        
        void MarkEnd()
        {
            tokTxt = null;
            tokEPos = readPos;
            tokELin = lNum;
            tokECol = cCol;
        }

        [SuppressMessage("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        int Peek()
        {
            int rslt, codeSv = code, cColSv = cCol, lNumSv = lNum, bPosSv = buffer.Pos;
            GetCode(); rslt = code;
            lNum = lNumSv; cCol = cColSv; code = codeSv; buffer.Pos = bPosSv;
            return rslt;
        }

        // ==============================================================
        // =====    Initialization of string-based input buffers     ====
        // ==============================================================

        /// <summary>
        /// Create and initialize a StringBuff buffer object for this scanner
        /// </summary>
        /// <param name="source">the input string</param>
        /// <param name="offset">starting offset in the string</param>
        [SuppressMessage("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        public void SetSource(string source, int offset)
        {
            this.buffer = ScanBuff.GetBuffer(source);
            this.buffer.Pos = offset;
            this.lNum = 0;
            this.code = '\n'; // to initialize yyline, yycol and lineStart
            GetCode();
        }

        // ================ LineBuffer Initialization ===================
        /// <summary>
        /// Create and initialize a LineBuff buffer object for this scanner
        /// </summary>
        /// <param name="source">the list of input strings</param>
        [SuppressMessage("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        public void SetSource(IList<string> source)
        {
            this.buffer = ScanBuff.GetBuffer(source);
            this.code = '\n'; // to initialize yyline, yycol and lineStart
            this.lNum = 0;
            GetCode();
        }

#if !NOFILES        
        // =============== StreamBuffer Initialization ==================

        /// <summary>
        /// Create and initialize a StreamBuff buffer object for this scanner.
        /// StreamBuff is buffer for 8-bit byte files.
        /// </summary>
        /// <param name="source">the input byte stream</param>
        [SuppressMessage("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        public void SetSource(Stream source)
        {
            this.buffer = ScanBuff.GetBuffer(source);
            this.lNum = 0;
            this.code = '\n'; // to initialize yyline, yycol and lineStart
            GetCode();
        }
        
#if !BYTEMODE
        // ================ TextBuffer Initialization ===================

        /// <summary>
        /// Create and initialize a TextBuff buffer object for this scanner.
        /// TextBuff is a buffer for encoded unicode files.
        /// </summary>
        /// <param name="source">the input text file</param>
        /// <param name="fallbackCodePage">Code page to use if file has
        /// no BOM. For 0, use machine default; for -1, 8-bit binary</param>
        [SuppressMessage("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        public void SetSource(Stream source, int fallbackCodePage)
        {
            this.buffer = ScanBuff.GetBuffer(source, fallbackCodePage);
            this.lNum = 0;
            this.code = '\n'; // to initialize yyline, yycol and lineStart
            GetCode();
        }
#endif // !BYTEMODE
#endif // !NOFILES
        
        // ==============================================================

#if BABEL
        //
        //  Get the next token for Visual Studio
        //
        //  "state" is the inout mode variable that maintains scanner
        //  state between calls, using the EolState property. In principle,
        //  if the calls of EolState are costly set could be called once
        //  only per line, at the start; and get called only at the end
        //  of the line. This needs more infrastructure ...
        //
        public int GetNext(ref int state, out int start, out int end)
        {
                Token next;
            int s, e;
            s = state;        // state at start
            EolState = state;
                next = (Token)Scan();
            state = EolState;
            e = state;       // state at end;
            start = tokPos;
            end = tokEPos - 1; // end is the index of last char.
            return (int)next;
        }        
#endif // BABEL

        // ======== AbstractScanner<> Implementation =========

        [SuppressMessage("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        [SuppressMessage("Microsoft.Naming", "CA1709:IdentifiersShouldBeCasedCorrectly", MessageId = "yylex")]
        [SuppressMessage("Microsoft.Naming", "CA1704:IdentifiersShouldBeSpelledCorrectly", MessageId = "yylex")]
        public override int yylex()
        {
            // parserMax is set by reflecting on the Tokens
            // enumeration.  If maxParseToken is defined
            // that is used, otherwise int.MaxValue is used.
            int next;
            do { next = Scan(); } while (next >= parserMax);
            return next;
        }
        
        [SuppressMessage("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        int yypos { get { return tokPos; } }
        
        [SuppressMessage("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        int yyline { get { return tokLin; } }
        
        [SuppressMessage("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        int yycol { get { return tokCol; } }

        [SuppressMessage("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        [SuppressMessage("Microsoft.Naming", "CA1709:IdentifiersShouldBeCasedCorrectly", MessageId = "yytext")]
        [SuppressMessage("Microsoft.Naming", "CA1704:IdentifiersShouldBeSpelledCorrectly", MessageId = "yytext")]
        public string yytext
        {
            get 
            {
                if (tokTxt == null) 
                    tokTxt = buffer.GetString(tokPos, tokEPos);
                return tokTxt;
            }
        }

        /// <summary>
        /// Discards all but the first "n" codepoints in the recognized pattern.
        /// Resets the buffer position so that only n codepoints have been consumed;
        /// yytext is also re-evaluated. 
        /// </summary>
        /// <param name="n">The number of codepoints to consume</param>
        [SuppressMessage("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        void yyless(int n)
        {
            buffer.Pos = tokPos;
            // Must read at least one char, so set before start.
            cCol = tokCol - 1; 
            GetCode();
            // Now ensure that line counting is correct.
            lNum = tokLin;
            // And count the rest of the text.
            for (int i = 0; i < n; i++) GetCode();
            MarkEnd();
        }
       
        //
        //  It would be nice to count backward in the text
        //  but it does not seem possible to re-establish
        //  the correct column counts except by going forward.
        //
        /// <summary>
        /// Removes the last "n" code points from the pattern.
        /// </summary>
        /// <param name="n">The number to remove</param>
        [SuppressMessage("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        void _yytrunc(int n) { yyless(yyleng - n); }
        
        //
        // This is painful, but we no longer count
        // codepoints.  For the overwhelming majority 
        // of cases the single line code is fast, for
        // the others, well, at least it is all in the
        // buffer so no files are touched. Note that we
        // can't use (tokEPos - tokPos) because of the
        // possibility of surrogate pairs in the token.
        //
        /// <summary>
        /// The length of the pattern in codepoints (not the same as 
        /// string-length if the pattern contains any surrogate pairs).
        /// </summary>
        [SuppressMessage("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        [SuppressMessage("Microsoft.Naming", "CA1709:IdentifiersShouldBeCasedCorrectly", MessageId = "yyleng")]
        [SuppressMessage("Microsoft.Naming", "CA1704:IdentifiersShouldBeSpelledCorrectly", MessageId = "yyleng")]
        public int yyleng
        {
            get {
                if (tokELin == tokLin)
                    return tokECol - tokCol;
                else
#if BYTEMODE
                    return tokEPos - tokPos;
#else
                {
                    int ch;
                    int count = 0;
                    int save = buffer.Pos;
                    buffer.Pos = tokPos;
                    do {
                        ch = buffer.Read();
                        if (!char.IsHighSurrogate((char)ch)) count++;
                    } while (buffer.Pos < tokEPos && ch != ScanBuff.EndOfFile);
                    buffer.Pos = save;
                    return count;
                }
#endif // BYTEMODE
            }
        }
        
        // ============ methods available in actions ==============

        [SuppressMessage("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal int YY_START {
            get { return currentScOrd; }
            set { currentScOrd = value; 
                  currentStart = startState[value]; 
            } 
        }
        
        [SuppressMessage("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal void BEGIN(int next) {
            currentScOrd = next;
            currentStart = startState[next];
        }

        // ============== The main tokenizer code =================

        int Scan() {
// User-specified prolog to scan()
LexSpan comStart = null;
    LexSpan errStart = null;
    LexSpan errEnd   = null;
    int braceNestingLevel = 0;
// End, user-specified prolog
            try {
                for (; ; ) {
                    int next;              // next state to enter
#if LEFTANCHORS
                    for (;;) {
                        // Discard characters that do not start any pattern.
                        // Must check the left anchor condition after *every* GetCode!
                        state = ((cCol == 0) ? anchorState[currentScOrd] : currentStart);
                        if ((next = NextState()) != goStart) break; // LOOP EXIT HERE...
                        GetCode();
                    }
                    
#else // !LEFTANCHORS
                    state = currentStart;
                    while ((next = NextState()) == goStart) {
                        // At this point, the current character has no
                        // transition from the current state.  We discard 
                        // the "no-match" char.   In traditional LEX such 
                        // characters are echoed to the console.
                        GetCode();
                    }
#endif // LEFTANCHORS                    
                    // At last, a valid transition ...    
                    MarkToken();
                    state = next;
                    GetCode();                    
#if BACKUP
                    bool contextSaved = false;
                    while ((next = NextState()) > eofNum) { // Exit for goStart AND for eofNum
                        if (state <= maxAccept && next > maxAccept) { // need to prepare backup data
                            // Store data for the *latest* accept state that was found.
                            SaveStateAndPos( ref ctx );
                            contextSaved = true;
                        }
                        state = next;
                        GetCode();
                    }
                    if (state > maxAccept && contextSaved)
                        RestoreStateAndPos( ref ctx );
#else  // BACKUP
                    while ((next = NextState()) > eofNum) { // Exit for goStart AND for eofNum
                         state = next;
                         GetCode();
                    }
#endif // BACKUP
                    if (state <= maxAccept) {
                        MarkEnd();
#region ActionSwitch
#pragma warning disable 162, 1522
    switch (state)
    {
        case eofNum:
            switch (currentStart) {
                case 124:
yy_pop_state(); yyless(0);
                    break;
                case 61:
Error(53, comStart); /* This comment is unterminated */
                    break;
                case 134:
if (braceNestingLevel != 0)
                                  Error(55, TokenSpan()); 
                              yy_pop_state(); 
                              yyless(0); 
                              return (int)Token.codeEnd;
                    break;
            }
            if (yywrap())
                return (int)Token.EOF;
            break;
        case 1: // Recognized '{NotWh}',	Shortest string "/"
        case 2: // Recognized '{NotWh}',	Shortest string "*"
        case 3: // Recognized '{NotWh}',	Shortest string "^%"
        case 8: // Recognized '{NotWh}',	Shortest string "'"
        case 9: // Recognized '{NotWh}',	Shortest string "\""
        case 21: // Recognized '{NotWh}',	Shortest string "%"
        case 23: // In <TheRules> Recognized '{NotWh}',	Shortest string "^%"
        case 27: // In <TheRules> Recognized '{NotWh}',	Shortest string "\""
        case 33: // In <TheRules> Recognized '{NotWh}',	Shortest string "%"
        case 71: // In <CodeBlock> Recognized '{NotWh}',	Shortest string "'"
Error(57, TokenSpan());
            break;
        case 4: // Recognized '{OpChars}',	Shortest string "{"
return (int)(yytext[0]);
            break;
        case 5: // Recognized '{Ident}',	Shortest string "G"
return (int)Token.ident;
            break;
        case 6: // Recognized '{Number}',	Shortest string "8"
        case 7: // Recognized '{Number}',	Shortest string "0"
yylval.iVal = ParseDecimal(yytext); return (int)Token.number;
            break;
        case 10: // Recognized '{BadStr}/[\r\n]',	Shortest string "\"\r"
_yytrunc(1); 
Error(58, TokenSpan());
            break;
        case 11: // Recognized '{LitStr}',	Shortest string "\"\""
return (int)Token.litstring;
            break;
        case 12: // Recognized '{LitChr}',	Shortest string "'/'"
return (int)Token.litchar;
            break;
        case 13: // Recognized '{HexNumber}',	Shortest string "0x8"
yylval.iVal = ParseHexaDec(yytext); return (int)Token.number;
            break;
        case 14: // Recognized '%{NotWh}',	Shortest string "%/"
Error(50, TokenSpan());
            break;
        case 15: // Recognized '^%%',	Shortest string "^%%"
yy_clear_stack();
                              BEGIN(TheRules); 
                              yy_push_state(ShouldBeBlank); errStart = null;
                              return (int)Token.kwPCPC;
            break;
        case 16: // Recognized '^%\{',	Shortest string "^%{"
yy_push_state(Prolog); 
                              yy_push_state(ShouldBeBlank); errStart = null;
                              return (int)Token.kwLbrace;
            break;
        case 17: // Recognized '^%{Ident}',	Shortest string "^%G"
{
                                  Token kWord = GetKeyword(yytext); 
                                  if (kWord == Token.kwOutput || kWord == Token.kwImportTokens)
                                      BEGIN(GetPath);
                                  return (int)kWord;
                              }
            break;
        case 18: // Recognized '^%\}',	Shortest string "^%}"
return (int)Token.kwRbrace; /* But a syntax error! */
            break;
        case 19: // Recognized '{OneLineCmnt}',	Shortest string "//"
/* skip */
            break;
        case 20: // Recognized '{CmntStrt}',	Shortest string "/*"
        case 57: // In <GetPath> Recognized '{CmntStrt}',	Shortest string "/*"
yy_push_state(Comment); 
                              comStart = TokenSpan(); 
                              /* And no token returned */
            break;
        case 22: // Recognized '\%{Ident}',	Shortest string "%G"
{   // An error, but attempt recovery
                                  Token kWord = GetKeyword(yytext); 
                                  if (kWord != Token.errTok)
                                      Error(59, TokenSpan());
                                  if (kWord == Token.kwOutput || kWord == Token.kwImportTokens)
                                      BEGIN(GetPath);
                                  return (int)kWord;
                              }
            break;
        case 24: // In <TheRules> Recognized '\{',	Shortest string "{"
yy_push_state(Action); 
                        braceNestingLevel = 1; 
                        return (int)'{';
            break;
        case 25: // In <TheRules> Recognized '^{Ident}',	Shortest string "^G"
return (int)Token.anchoredSymbol;
            break;
        case 26: // In <TheRules> Recognized '\'',	Shortest string "'"
Error(58, TokenSpan());
            break;
        case 28: // In <TheRules> Recognized '{OpChars}',	Shortest string ","
return (int)(yytext[0]);
            break;
        case 29: // In <TheRules> Recognized '{LitStr}',	Shortest string "\"\""
return (int)Token.litstring;
            break;
        case 30: // In <TheRules> Recognized '{LitChr}',	Shortest string "'/'"
return (int)Token.litchar;
            break;
        case 31: // In <TheRules> Recognized '^%%',	Shortest string "^%%"
yy_clear_stack();
                        BEGIN(TheEpilog); 
                        yy_push_state(ShouldBeBlank); errStart = null;
                        return (int)Token.kwPCPC;
            break;
        case 32: // In <TheRules> Recognized '\%{Ident}',	Shortest string "%G"
return (int)GetKeyword(yytext);
            break;
        case 34: // In <TheRules> Recognized '{Ident}',	Shortest string "G"
return (int)Token.ident;
            break;
        case 35: // In <TheEpilog> Recognized '.',	Shortest string "/"
        case 36: // In <TheEpilog> Recognized '.',	Shortest string "\t"
        case 37: // In <TheEpilog> Recognized '.',	Shortest string "%"
        case 38: // In <TheEpilog> Recognized '.',	Shortest string "\""
        case 58: // In <Prolog> Recognized '.',	Shortest string "^%"
yy_push_state(CodeBlock); yyless(0); return (int)Token.codeStart;
            break;
        case 39: // In <TheEpilog> Recognized '{OneLineCmnt}',	Shortest string "//"
yy_push_state(CodeBlock);  
                              return (int)Token.codeStart;
            break;
        case 40: // In <TheEpilog> Recognized '{CmntStrt}',	Shortest string "/*"
yy_push_state(CodeBlock); 
                              yy_push_state(Comment); 
                              comStart = TokenSpan(); 
                              return (int)Token.codeStart;
            break;
        case 41: // In <GetPath> Recognized '{Eol}',	Shortest string ""
        case 44: // In <GetPath> Recognized '{Eol}',	Shortest string "\r"
BEGIN(0);
            break;
        case 42: // In <GetPath> Recognized '{NotWh}+',	Shortest string "/"
        case 43: // In <GetPath> Recognized '{NotWh}+',	Shortest string "*"
        case 45: // In <GetPath> Recognized '{NotWh}+',	Shortest string "\""
        case 46: // In <GetPath> Recognized '{NotWh}+',	Shortest string "@"
        case 48: // In <GetPath> Recognized '{NotWh}+',	Shortest string "@\""
        case 49: // In <GetPath> Recognized '{NotWh}+',	Shortest string "@\"\\"
        case 54: // In <GetPath> Recognized '{NotWh}+',	Shortest string "\"\\"
return (int)Token.filePath;
            break;
        case 47: // In <GetPath> Recognized '={NotWh}*',	Shortest string "="
yyless(1); return (int)'=';
            break;
        case 50: // In <GetPath> Recognized '{VrbStr}',	Shortest string "@\"\""
        case 51: // In <GetPath> Recognized '{VrbStr}',	Shortest string "@\"\\\""
        case 52: // In <GetPath> Recognized '{VrbStr}',	Shortest string "@\"\t\""
        case 53: // In <GetPath> Recognized '{VrbStr}',	Shortest string "@\"\t\\\""
return (int)Token.verbatim;
            break;
        case 55: // In <GetPath> Recognized '{LitStr}',	Shortest string "\"\""
        case 56: // In <GetPath> Recognized '{LitStr}',	Shortest string "\"\x20\""
return (int)Token.litstring;
            break;
        case 59: // In <Prolog> Recognized '^%\}',	Shortest string "^%}"
if (braceNestingLevel != 0) {
                                  Error(55, TokenSpan()); braceNestingLevel = 0;
                              }
                              else {
                                  yy_pop_state(); return (int)Token.kwRbrace; 
                              }
            break;
        case 60: // In <Action> Recognized '\}',	Shortest string "}"
yy_pop_state(); return (int)'}';
            break;
        case 61: // In <Comment> Recognized '{ABStar}',	Shortest string ""
        case 62: // In <Comment> Recognized '{ABStar}',	Shortest string "/"
        case 63: // In <Comment> Recognized '\*',	Shortest string "*"
        case 64: // In <Comment> Recognized '{ABStar}',	Shortest string "%"
        case 65: // In <Comment> Recognized '{ABStar}',	Shortest string "\""
        case 66: // In <Comment> Recognized '{ABStar}',	Shortest string "\"\\"
/* skip */
            break;
        case 67: // In <Comment> Recognized '{CmntEnd}',	Shortest string "*/"
yy_pop_state();
                         // If comment has obscured one or more EOL then ...  
                         if (YY_START == ShouldBeBlank) {
                             if (errStart != null) {
                                 Error(54, errStart.Merge(errEnd));
                                 errStart = null;
                             } else if (lNum > comStart.startLine) 
                                 yy_pop_state();
                         }
                         /* And no token returned */
            break;
        case 68: // In <CodeBlock> Recognized '\/',	Shortest string "/"
        case 69: // In <CodeBlock> Recognized '\%',	Shortest string "^%"
        case 73: // In <CodeBlock> Recognized '@',	Shortest string "@"
        case 75: // In <CodeBlock> Recognized '{VrbStr}',	Shortest string "@\"\\\""
        case 76: // In <CodeBlock> Recognized '{LitStr}',	Shortest string "\"\""
        case 77: // In <CodeBlock> Recognized '\%{CodeSkip}+',	Shortest string "\t"
        case 80: // In <CodeBlock> Recognized '\%',	Shortest string "%"
/* skip */
            break;
        case 70: // In <CodeBlock> Recognized '\{',	Shortest string "{"
braceNestingLevel++;
            break;
        case 72: // In <CodeBlock> Recognized '{BadStr}',	Shortest string "\""
Error(58, TokenSpan());
            break;
        case 74: // In <CodeBlock> Recognized '\}',	Shortest string "}"
if (braceNestingLevel == 0 && 
                                       yy_top_state() == Action) {
                                  yy_pop_state();
                                  yyless(0);
                                  return (int)Token.codeEnd;
                              }
                              else
                                  braceNestingLevel--;
            break;
        case 78: // In <CodeBlock> Recognized '^%%',	Shortest string "^%%"
for ( ; ; ) {
                                  yy_pop_state();
                                  switch (YY_START)
                                  {
                                    case INITIAL: 
                                        Error(60, TokenSpan()); 
                                        return (int)Token.kwPCPC;
                                    case TheRules: 
                                        Error(60, TokenSpan());
                                        return (int)Token.kwPCPC;
                                    default: break; 
                                  }
                              }
            break;
        case 79: // In <CodeBlock> Recognized '^%\}',	Shortest string "^%}"
if (yy_top_state() != Prolog) {
                                  Error(56, TokenSpan()); yy_clear_stack(); BEGIN(Prolog);
                              } else if (braceNestingLevel != 0) {
                                  Error(55, TokenSpan());
                              } else {
                                  yy_pop_state();
                              } 
                              yyless(0); return (int)Token.codeEnd;
            break;
        case 81: // In <ShouldBeBlank> Recognized '{Eol}',	Shortest string ""
        case 84: // In <ShouldBeBlank> Recognized '{Eol}',	Shortest string "\r"
if (errStart != null)
                                  Error(54, errStart.Merge(errEnd)); 
                              yy_pop_state();
            break;
        case 82: // In <ShouldBeBlank> Recognized '{NotWh}',	Shortest string "/"
        case 83: // In <ShouldBeBlank> Recognized '{NotWh}',	Shortest string "*"
        case 85: // In <ShouldBeBlank> Recognized '{NotWh}',	Shortest string "%"
        case 86: // In <ShouldBeBlank> Recognized '{NotWh}',	Shortest string "\""
{
                                LexSpan cSpan = TokenSpan(); /* Only white space goes here */
                                errEnd = cSpan;
                                if (errStart == null) errStart = cSpan;
                              }
            break;
        default:
            break;
    }
#pragma warning restore 162, 1522
#endregion
                    }
                }
            } // end try
            finally {
// User-specified epilog to scan()
yylloc = new LexSpan(tokLin, tokCol, tokELin, tokECol, tokPos, tokEPos, buffer);
// End, user-specified epilog
            } // end finally
        }

#if BACKUP
        void SaveStateAndPos(ref Context ctx) {
            ctx.bPos  = buffer.Pos;
            ctx.rPos  = readPos;
            ctx.cCol  = cCol;
            ctx.lNum  = lNum;
            ctx.state = state;
            ctx.cChr  = code;
        }

        void RestoreStateAndPos(ref Context ctx) {
            buffer.Pos = ctx.bPos;
            readPos = ctx.rPos;
            cCol  = ctx.cCol;
            lNum  = ctx.lNum;
            state = ctx.state;
            code  = ctx.cChr;
        }
#endif  // BACKUP

        // ============= End of the tokenizer code ================

#if STACK        
        [SuppressMessage("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal void yy_clear_stack() { scStack.Clear(); }
        
        [SuppressMessage("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal int yy_top_state() { return scStack.Peek(); }
        
        internal void yy_push_state(int state)
        {
            scStack.Push(currentScOrd);
            BEGIN(state);
        }
        
        internal void yy_pop_state()
        {
            // Protect against input errors that pop too far ...
            if (scStack.Count > 0) {
				int newSc = scStack.Pop();
				BEGIN(newSc);
            } // Otherwise leave stack unchanged.
        }
 #endif // STACK

        [SuppressMessage("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal void ECHO() { Console.Out.Write(yytext); }
        
#region UserCodeSection

/* User Code is all in ScanHelper.cs */

#endregion
    } // end class $Scanner


} // end namespace
